# Generated by Django 5.1.2 on 2024-10-30 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('max_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('weather', models.CharField()),
                ('hourly_temperature', models.JSONField(default=None, null=True)),
            ],
        ),
    ]
