# Generated by Django 5.1.2 on 2024-10-30 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='max_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='min_temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='weather',
            field=models.CharField(null=True),
        ),
    ]
