# Generated by Django 5.1.2 on 2024-10-30 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_site', '0003_alter_forecast_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, unique=True),
        ),
    ]
