# Generated by Django 5.1.2 on 2024-10-31 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_site', '0004_alter_forecast_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='date',
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='precipitation_chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='hourly_temperature',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='weather',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather_site.location'),
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_site.location')),
            ],
        ),
    ]
