# Generated by Django 5.1.2 on 2024-11-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_site', '0006_forecast_weather_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='weather_image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
