# Generated by Django 5.1.2 on 2024-11-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_site', '0010_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
